"""added public/private status attribute to subreddit

Revision ID: 7e8c8d87ad4f
Revises: 35ccc8f964b0
Create Date: 2025-03-21 19:53:34.227338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8c8d87ad4f'
down_revision: Union[str, None] = '35ccc8f964b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum('public', 'private', name='subreddit_status')

def upgrade() -> None:
    """Upgrade schema."""
    status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('status', sa.Enum('public', 'private', name='subreddit_status'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subreddits', 'status')
    # ### end Alembic commands ###
    status_enum.drop(op.get_bind())
