"""Fixed many-to-many relationship between User and Subreddit3

Revision ID: 5c671cf7368b
Revises: b7bed61625b6
Create Date: 2025-03-19 18:26:50.131987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c671cf7368b'
down_revision: Union[str, None] = 'b7bed61625b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
