"""Fixed many-to-many relationship between User and Subreddit

Revision ID: b7bed61625b6
Revises: ba3c7bae7a62
Create Date: 2025-03-19 18:09:27.032202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bed61625b6'
down_revision: Union[str, None] = 'ba3c7bae7a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
