"""Fixed many-to-many relationship between User and Subreddit

Revision ID: ba3c7bae7a62
Revises: eb925eed769b
Create Date: 2025-03-19 17:34:10.274346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba3c7bae7a62'
down_revision: Union[str, None] = 'eb925eed769b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subreddit', 'role',
               existing_type=postgresql.ENUM('member', 'moderator', name='role_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_subreddit', 'role',
               existing_type=postgresql.ENUM('member', 'moderator', name='role_enum'),
               nullable=True)
    # ### end Alembic commands ###
